new_player_commands:
# These commands will only be run when players join the server for the first time.
#  "help":
#    run_as: player

returning_player_commands:
# These commands are run for players who've join the server before.
#  "motd":
#    run_as: player